### ISSUE TITLE
How to get the model weights

### ISSUE THREAD

**Issue by cuongvng** [ViswanathaReddyGajjala/centerface-pytorch#6]
Hi, I would like to know how you got the PyTorch model weights. Did you convert from any of the [Star Cloud Centerface models](https://github.com/Star-Clouds/CenterFace/tree/master/models)?

**Comment by ViswanathaReddyGajjala** [comment]
Yes, I have used the pre-trained model from [Star Cloud Centerface](https://github.com/Star-Clouds/CenterFace/blob/master/models/onnx/centerface.onnx). I have used the netron to visualize the onnx model and ported the onnx weights to pytorch.
